# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = [
    "go.sum",
    "ciphers.go",
    "ciphers_test.go",
    "testdata/draft-ietf-httpbis-http2.xml",
]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
ConnTLSer = "ConnTLSer"
flate = "flate"
TestCompressFlateSerial = "TestCompressFlateSerial"
testCompressFlate = "testCompressFlate"
TestCompressFlateConcurrent = "TestCompressFlateConcurrent"
trUe = "trUe"
OPTIO = "OPTIO"
contant = "contant"
referer = "referer"
HeaderReferer = "HeaderReferer"
expectedReferer = "expectedReferer"
Referer = "Referer"
henc = "henc"
6ba0 = "6ba0"
5ba9 = "5ba9"
clen = "clen"